### ISSUE TITLE
Add information about userid

### ISSUE THREAD

**Issue by tetafro** [ndrewnee/go-yamusic#7]
User id is used in many methods, but it's not clear from docs how to get it. Can you please add a recommended way?

Btw, Python library [fetches and stores](https://github.com/MarshalX/yandex-music-api/blob/main/yandex_music/client.py#L152) account information on init to avoid asking user to provide user id in each method.

---

Getting token is also not clear, but it's probably because there's no official way to get. Leaving [this discussion](https://github.com/MarshalX/yandex-music-api/discussions/513) here in case somebody looks for it as me.

**Comment by hrueschwein** [comment]
I used this way:

1. Make this request:

```
curl https://api.music.yandex.net/users/box@example.net
```
Instead of `box@example.net`, of course, put email on which yandex account registered.

2. Curl will print JSON map. Find `result.uid` field — there's your ID.

**Comment by tetafro** [comment]
I ended up with this
```go
ya := yamusic.NewClient(yamusic.AccessToken(0, token))
status, _, err := ya.Account().GetStatus(ctx)
if err != nil {}
	// handle
}
ya.SetUserID(status.Result.Account.UID)
```
